# Generated by Django 3.2.5 on 2021-08-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
